# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-15 17:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loginandregistration', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='description',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='user_level',
            field=models.IntegerField(null=True),
        ),
    ]
